apiVersion: apps/v1
kind: Deployment

metadata:
  name: sentiment-blue-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: sentiment-api
      slot: blue

  template:
    metadata:
      labels:
        app: sentiment-api
        slot: blue

    spec:
      containers:
      - name: sentiment-api

        image: zaibjahan200/sentiment-api:unstable

        ports:
        - containerPort: 5000

        volumeMounts:
        - mountPath: /app/logs
          name: logs

      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: sentiment-logs-pvc